// facts.mjs - one generated sheet that every published number comes from.
//
// These figures have been regenerated four times as defects were found, and
// each time a stale copy survived somewhere: in the README, in a slide, in a
// meta description. A number that is retyped into three documents will
// disagree with itself eventually, and the disagreement is what a reviewer
// notices first.
//
// So: this emits docs/FACTS.md from the cohort file and the live corpus, and
// CI asserts it is not stale. Anything quoting a figure quotes this.
//
// Usage: node --env-file=.env scripts/facts.mjs

import fs from 'node:fs';
import * as db from '../apps/api/src/db.js';
import { DEFAULT_RECORDING, getRecording } from '../apps/api/src/recordings.js';

const cohort = JSON.parse(fs.readFileSync('apps/web/data/cohort.json', 'utf8'));
const p = cohort.primary;
const rec = getRecording(DEFAULT_RECORDING);

let corpus = null;
const pool = db.createPool(process.env.DATABASE_URL);
if (pool) {
  try { corpus = (await db.corpusSummary(pool, DEFAULT_RECORDING)).aggregate; }
  catch (e) { console.error('corpus unavailable:', e.message); }
  await pool.end();
}

const n = corpus ? Number(corpus.targets) : null;
const pctOf = (x) => (n ? ((100 * Number(x)) / n).toFixed(1) : '?');
const r1 = (x) => Number(x).toFixed(1);
const r2 = (x) => Number(x).toFixed(2);

const out = `# Facts

Generated by \`node --env-file=.env scripts/facts.mjs\`. Do not edit by hand.
CI asserts this file is not stale, so every figure quoted anywhere in this
repository can be traced to one run.

Generated: ${new Date().toISOString().slice(0, 10)}

## The cohort

| | |
|---|---|
| Subjects measured | ${p.subjects} |
| Postural recordings analysed | ${p.recordings.toLocaleString()} |
| Containing a detectable tremor | ${p.clearing} (${(p.clearRate * 100).toFixed(1)}%), from ${p.subjectsClearing} subjects |
| Median amplitude of those | ${r2(p.amplitudeMm.median)} mm |
| Median cursor travel at 800 cpi | ${r1(p.cursorExcursionPx800.median)} px |
| Largest measured | ${r2(p.amplitudeMm.max)} mm |
| Wider than the whole 24 px target | ${p.exceedsWholeTarget24} of ${p.clearing} |
| Hold a 24 px target under 95% of the time | ${p.below95At24} of ${p.clearing} |
| Miss more often than they hit | ${p.below50At24} of ${p.clearing} |
| Still under 95% at the 44 px AAA size | ${p.below95At44} of ${p.clearing} |
| Median hold of a 24 px target | ${(p.hold24At800.median * 100).toFixed(0)}% |

Highest detection rate by condition: ${Object.entries(p.byCondition)
  .sort((a, b) => b[1].clearRate - a[1].clearRate)[0][0]} at ${(Object.entries(p.byCondition)
  .sort((a, b) => b[1].clearRate - a[1].clearRate)[0][1].clearRate * 100).toFixed(1)}%.

## The recording the corpus is judged against

| | |
|---|---|
| Subject | ${rec.meta.subject} (${rec.meta.condition}) |
| Task | ${rec.meta.taskLabel}, ${rec.meta.wrist} wrist |
| Frequency | ${rec.meta.hz} Hz |
| Amplitude | ${rec.meta.p2pMm} mm, which is ${rec.meta.cursorPxAt800} px at 800 cpi |
| Rank among the ${p.clearing} detected tremors | median |

${corpus ? `## The corpus

| | |
|---|---|
| Sites measured | ${corpus.sites} |
| Interactive controls | ${n.toLocaleString()} |
| Pass WCAG 2.5.8 | ${pctOf(n - corpus.fail_standard)}% |
| Fail it outright | ${corpus.fail_standard} (${pctOf(corpus.fail_standard)}%) |
| Pass it and cannot be held | ${corpus.pass_standard_fail_hand} (${pctOf(corpus.pass_standard_fail_hand)}%) |
| Held under 95% of the time | ${corpus.below_95} (${pctOf(corpus.below_95)}%) |
| Missed more often than hit | ${corpus.below_50} (${pctOf(corpus.below_50)}%) |
| Bound by height | ${corpus.limited_by_height} |
| Bound by width | ${corpus.limited_by_width} |
| Median control | ${Math.round(corpus.median_w)} by ${Math.round(corpus.median_h)} px |
| Median hold | ${(corpus.median_hold * 100).toFixed(0)}% |
` : '## The corpus\n\nUnavailable: no DATABASE_URL when this was generated.\n'}
## Method accuracy

Produced by \`node scripts/validate.mjs\`, which CI runs with gates.
See that script's output for the current figures.

## One-line summary

${corpus ? `${corpus.sites} live sites, ${n.toLocaleString()} interactive controls: ${pctOf(n - corpus.fail_standard)}% pass WCAG 2.5.8 and ${pctOf(corpus.pass_standard_fail_hand)}% of those cannot be reliably held by a median clinically recorded tremor.` : '(corpus unavailable)'}
`;

fs.mkdirSync('docs', { recursive: true });
fs.writeFileSync('docs/FACTS.md', out);
console.log(out.split('\n').slice(-3).join('\n'));
